#Exploring the Determinants of Economic Growth in North Africa: An Analysis of Key Variables
The README file offers a concise overview of the project, outlining the data sources, research methods, and significant findings. It acts as a useful reference to familiarize yourself with the organization of the repository and the outputs presented within it.


##Summary
In this project, the focus was on identifying the key variables that contribute to economic growth in North African countries, specifically Algeria, Egypt, Libya, Morocco, and Tunisia. To achieve this, the project considered a range of different variables from both economic and non-economic spheres, including trade, foreign direct investment (FDI), political stability, and education.
The analysis revealed that there is no single variable that can be identified as the sole contributor to GDP growth in these countries. Rather, it is a combination of different variables that come into play. However, the research did identify political stability and trade openness as being particularly important factors that have a significant impact on economic growth.
In summary, the project sought to provide a comprehensive understanding of the factors that underpin economic growth in North African countries, with a particular focus on identifying the key variables that policymakers should prioritize in their efforts to promote growth and development in the region.

##Data
The data utilized in my research was obtained from The Humanitarian Data Exchange, which provides access to several indicators by country. I primarily relied on a comprehensive dataset titled "Economic, Social, Environmental, Health, Education, Development, and Energy" containing data from the World Bank's data portal. This dataset covers various topics such as Agriculture and Rural Development, Aid Effectiveness, Economy and Growth, Education, Energy and Mining, Environment, Financial Sector, Health, Infrastructure, Social Protection and Labor, Poverty, Private Sector, Public Sector, Science and Technology, Social Development, Urban Development, Gender, Climate Change, External Debt, and Trade.
My analysis focused on two main metrics, namely Economy and Growth and Education. Economic growth is essential to promoting economic development, and data on measures such as gross domestic product (GDP) and gross national income (GNI), as well as factors such as capital stock, employment, investment, savings, consumption, government spending, imports, and exports, can help policymakers gain a better understanding of their country's economic situation and guide any efforts to improve it.
Education is also critical for reducing poverty and inequality and laying the foundation for sustained economic growth. I obtained education-related data from the United Nations Educational, Scientific, and Cultural Organization (UNESCO) Institute for Statistics, which compiles data on education inputs, participation, efficiency, and outcomes.
Furthermore, I also looked at the political stability metric, for which I used the Worldwide Governance Indicators (WGI) project. The WGI project provides aggregate and individual governance indicators for over 200 countries and territories, covering six dimensions of governance: Voice and Accountability, Political Stability and Absence of Violence/Terrorism, Government Effectiveness, Regulatory Quality, Rule of Law, and Control of Corruption. These indicators are based on over 30 individual data sources produced by various organizations, including survey institutes, think tanks, non-governmental organizations, international organizations, and private sector firms.	

##Running Scripts

###*plot_gdp.py*
The code provided reads and cleans GDP per capita growth data for selected North African countries, specifically Algeria, Egypt, Morocco, Libya, and Tunisia, from a CSV file. It renames the "Egypt, Arab Rep." row to "Egypt" and filters the dataframe to only include GDP per capita growth (annual %) data for the years 2014 and later. The cleaned data is then pivoted so that each country is a column and each year is a row, and normalized to the base year of 2014. Finally, the code creates a line plot of the normalized GDP per capita growth rates for each country over time, with a title indicating the base year and axes labeled appropriately. The plot is saved as a PNG file and displayed. 
This code provides an analysis of the evolution of GDP per capita growth rate for selected North African countries with a focus on identifying trends in economic performance and providing insights into the factors driving economic growth in the region.
The final output is a graph that illustrates the changes in GDP per capita over time.
###*plot_trade.py*
This code analyzes trade data for selected North African countries to determine its influence on economic growth. The resulting graphs illustrate the trade balance for each country and how it has evolved over time, providing valuable insight into the impact of trade on the economic growth of these nations. Additionally, the analysis explores whether trade openness has a positive effect on GDP growth, which could explain the overall economic growth of a country.
###*plot_fdi.py*
The code aims to analyze the Foreign Direct Investment (FDI) data to determine its impact on economic growth. The analysis involves generating distinct bar graphs for each country, displaying the changes in FDI inflows relative to the years 2001, 2011, and 2021.
###*plot_education.py*
The graphics in this code aim to analyze the effect of education on economic growth in North African countries. The first graph shows the evolution of the Barro-Lee indicator for total years of schooling among individuals aged 25 and above in four North African countries (Tunisia, Egypt, Libya, and Algeria) from 1970 to 2018. The Barro-Lee indicator is a metric that represents the average years of total schooling for individuals aged 25 and above, and it is widely used in the analysis of the effect of education on economic growth. The graph helps to visualize the trend of education in North African countries over time.
The second graph is a scatter plot that displays the relationship between the Barro-Lee indicator for total years of schooling among individuals aged 25 and above and the GDP growth rate in North African countries. This plot helps to identify if there is a correlation between the level of education and economic growth in North African countries. The graph also provides an insight into whether investment in education is a good strategy for promoting economic growth in North African countries.
